# Generated by Django 5.1.1 on 2024-10-22 17:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='Без описания', max_length=500)),
                ('bonus', models.CharField(default='Без бонусов', max_length=200)),
                ('fact', models.CharField(default='Без факта', max_length=100)),
                ('cost', models.IntegerField(default=5000)),
                ('imageUrl', models.URLField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='BankApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалена'), ('created', 'Сформирована'), ('completed', 'Завершена'), ('rejected', 'Отклонена')], default='draft', max_length=50)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('apply_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('psrn_and_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_services', models.IntegerField(blank=True, null=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=500)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.bankapplication')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.bankoffer')),
            ],
            options={
                'db_table': 'comment',
                'unique_together': {('application', 'offer')},
            },
        ),
    ]
