# Generated by Django 5.1.1 on 2024-10-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankapplication',
            name='number_of_services',
        ),
        migrations.AddField(
            model_name='comment',
            name='account_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankoffer',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
